In [1]:
import pandas as pd
from data_builder import DataBuilder
from torch.utils.data import DataLoader
import numpy as np

In [33]:
def standardizer(input_array):
    mean = np.mean(input_array)
    std = np.std(input_array)
    standardized_array = (input_array - mean) / std
    return standardized_array

In [34]:
beam_break_data = pd.read_csv('/home/rachel/Desktop/mm-vae_ext2/data/master_binary.csv')
beam_break_data

/tmp/ipykernel_579290/1559551854.py:1: DtypeWarning: Columns (1,2,20079) have mixed types. Specify dtype option on import or set low_memory=False.
  beam_break_data = pd.read_csv('/home/rachel/Desktop/mm-vae_ext2/data/master_binary.csv')

,FlyID,Genotype_SpecSheet,Genotype (F>M),RunName,Monitor,Channel,StartMeta,EndMeta,TimeLen,t0,...,t20062,t20063,t20064,t20065,t20066,t20067,Average bout length/D,Activity/waking min,Genotype (FxM)_specsheet,Genotype (FxM)
0,M106_M118_Ch25,Londonxalrm_1_M,London>alrm,M106,118,25,139834 | 12 Dec 24 | 13:25:00 | 51 | 0 | 118 |...,161518 | 27 Dec 24 | 14:49:00 | 51 | 0 | 118 |...,21685,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,88.206897,2.891771,NaN,NaN
1,M106_M118_Ch26,Londonxalrm_1_M,London>alrm,M106,118,26,139834 | 12 Dec 24 | 13:25:00 | 51 | 0 | 118 |...,161518 | 27 Dec 24 | 14:49:00 | 51 | 0 | 118 |...,21685,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,90.576923,1.933168,NaN,NaN
2,M106_M118_Ch27,Londonxalrm_1_M,London>alrm,M106,118,27,139834 | 12 Dec 24 | 13:25:00 | 51 | 0 | 118 |...,161518 | 27 Dec 24 | 14:49:00 | 51 | 0 | 118 |...,21685,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,62.487179,2.523714,NaN,NaN
3,M106_M118_Ch28,Londonxalrm_1_M,London>alrm,M106,118,28,139834 | 12 Dec 24 | 13:25:00 | 51 | 0 | 118 |...,161518 | 27 Dec 24 | 14:49:00 | 51 | 0 | 118 |...,21685,0.0,...,0.0,4.0,0.0,0.0,0.0,0.0,216.083333,1.665618,NaN,NaN
4,M106_M118_Ch29,Londonxalrm_1_M,London>alrm,M106,118,29,139834 | 12 Dec 24 | 13:25:00 | 51 | 0 | 118 |...,161518 | 27 Dec 24 | 14:49:00 | 51 | 0 | 118 |...,21685,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,39.933333,2.639334,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1358,M96_M48_Ch28,elav>attp2vF,NaN,M96,48,28,161390 | 21 Nov 24 | 12:10:00 | 51 | 0 | 48 | ...,181531 | 5 Dec 24 | 11:51:00 | 51 | 0 | 48 | 0...,20142,0.0,...,2.0,1.0,3.0,2.0,1.0,1.0,86.413793,2.272366,NaN,NaN
1359,M96_M48_Ch29,elav>attp2vF,NaN,M96,48,29,161390 | 21 Nov 24 | 12:10:00 | 51 | 0 | 48 | ...,181531 | 5 Dec 24 | 11:51:00 | 51 | 0 | 48 | 0...,20142,0.0,...,2.0,2.0,1.0,1.0,2.0,2.0,28.743243,2.505122,NaN,NaN
1360,M96_M48_Ch30,elav>attp2vF,NaN,M96,48,30,161390 | 21 Nov 24 | 12:10:00 | 51 | 0 | 48 | ...,181531 | 5 Dec 24 | 11:51:00 | 51 | 0 | 48 | 0...,20142,0.0,...,0.0,1.0,1.0,0.0,1.0,1.0,26.519481,2.455212,NaN,NaN
1361,M96_M48_Ch31,elav>attp2vF,NaN,M96,48,31,161390 | 21 Nov 24 | 12:10:00 | 51 | 0 | 48 | ...,181531 | 5 Dec 24 | 11:51:00 | 51 | 0 | 48 | 0...,20142,0.0,...,3.0,0.0,1.0,1.0,0.0,1.0,48.088889,2.453503,NaN,NaN
1362,M96_M48_Ch32,elav>attp2vF,NaN,M96,48,32,161390 | 21 Nov 24 | 12:10:00 | 51 | 0 | 48 | ...,181531 | 5 Dec 24 | 11:51:00 | 51 | 0 | 48 | 0...,20142,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,49.071429,3.204082,NaN,NaN

In [10]:
beam_break_data['Genotype_SpecSheet'].isna().sum()

157

In [41]:
beam_break_data = beam_break_data.dropna(subset='Genotype_SpecSheet').reset_index(drop=True)
beam_break_data

,FlyID,Genotype_SpecSheet,Genotype (F>M),RunName,Monitor,Channel,StartMeta,EndMeta,TimeLen,t0,...,t20062,t20063,t20064,t20065,t20066,t20067,Average bout length/D,Activity/waking min,Genotype (FxM)_specsheet,Genotype (FxM)
0,M106_M118_Ch25,Londonxalrm_1_M,London>alrm,M106,118,25,139834 | 12 Dec 24 | 13:25:00 | 51 | 0 | 118 |...,161518 | 27 Dec 24 | 14:49:00 | 51 | 0 | 118 |...,21685,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,88.206897,2.891771,NaN,NaN
1,M106_M118_Ch26,Londonxalrm_1_M,London>alrm,M106,118,26,139834 | 12 Dec 24 | 13:25:00 | 51 | 0 | 118 |...,161518 | 27 Dec 24 | 14:49:00 | 51 | 0 | 118 |...,21685,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,90.576923,1.933168,NaN,NaN
2,M106_M118_Ch27,Londonxalrm_1_M,London>alrm,M106,118,27,139834 | 12 Dec 24 | 13:25:00 | 51 | 0 | 118 |...,161518 | 27 Dec 24 | 14:49:00 | 51 | 0 | 118 |...,21685,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,62.487179,2.523714,NaN,NaN
3,M106_M118_Ch28,Londonxalrm_1_M,London>alrm,M106,118,28,139834 | 12 Dec 24 | 13:25:00 | 51 | 0 | 118 |...,161518 | 27 Dec 24 | 14:49:00 | 51 | 0 | 118 |...,21685,0.0,...,0.0,4.0,0.0,0.0,0.0,0.0,216.083333,1.665618,NaN,NaN
4,M106_M118_Ch29,Londonxalrm_1_M,London>alrm,M106,118,29,139834 | 12 Dec 24 | 13:25:00 | 51 | 0 | 118 |...,161518 | 27 Dec 24 | 14:49:00 | 51 | 0 | 118 |...,21685,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,39.933333,2.639334,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1201,M96_M48_Ch28,elav>attp2vF,NaN,M96,48,28,161390 | 21 Nov 24 | 12:10:00 | 51 | 0 | 48 | ...,181531 | 5 Dec 24 | 11:51:00 | 51 | 0 | 48 | 0...,20142,0.0,...,2.0,1.0,3.0,2.0,1.0,1.0,86.413793,2.272366,NaN,NaN
1202,M96_M48_Ch29,elav>attp2vF,NaN,M96,48,29,161390 | 21 Nov 24 | 12:10:00 | 51 | 0 | 48 | ...,181531 | 5 Dec 24 | 11:51:00 | 51 | 0 | 48 | 0...,20142,0.0,...,2.0,2.0,1.0,1.0,2.0,2.0,28.743243,2.505122,NaN,NaN
1203,M96_M48_Ch30,elav>attp2vF,NaN,M96,48,30,161390 | 21 Nov 24 | 12:10:00 | 51 | 0 | 48 | ...,181531 | 5 Dec 24 | 11:51:00 | 51 | 0 | 48 | 0...,20142,0.0,...,0.0,1.0,1.0,0.0,1.0,1.0,26.519481,2.455212,NaN,NaN
1204,M96_M48_Ch31,elav>attp2vF,NaN,M96,48,31,161390 | 21 Nov 24 | 12:10:00 | 51 | 0 | 48 | ...,181531 | 5 Dec 24 | 11:51:00 | 51 | 0 | 48 | 0...,20142,0.0,...,3.0,0.0,1.0,1.0,0.0,1.0,48.088889,2.453503,NaN,NaN
1205,M96_M48_Ch32,elav>attp2vF,NaN,M96,48,32,161390 | 21 Nov 24 | 12:10:00 | 51 | 0 | 48 | ...,181531 | 5 Dec 24 | 11:51:00 | 51 | 0 | 48 | 0...,20142,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,49.071429,3.204082,NaN,NaN

In [3]:
beam_break_data.columns

Index(['FlyID', 'Genotype_SpecSheet', 'Genotype (F>M)', 'RunName', 'Monitor',
       'Channel', 'StartMeta', 'EndMeta', 'TimeLen', 't0',
       ...
       't20062', 't20063', 't20064', 't20065', 't20066', 't20067',
       'Average bout length/D', 'Activity/waking min',
       'Genotype (FxM)_specsheet', 'Genotype (FxM)'],
      dtype='object', length=20081)

In [4]:
beam_break_data['Genotype_SpecSheet'].unique()

array(['Londonxalrm_1_M', 'Londonxalrm_2_F', 'Londonxalrm_2_M',
       'Londonxalrm_3_F', 'Londonxalrm_3_M', 'Londonxattp2_1_F',
       'Londonxattp2_1_M', 'Londonxattp2_2_F', 'Londonxattp2_2_M',
       'Londonxattp2_3_F', 'Londonxattp2_3_M', 'Londonxattp40_2_F',
       'Londonxattp40_2_M', 'Londonxattp40_3_F', 'Londonxattp40_3_M',
       'Londonxrepo_1_F', 'Londonxrepo_2_F', 'Londonxrepo_2_M',
       'Londonxrepo_3_F', 'Londonxrepo_3_M', 'SwedArcxattp2_1_F',
       'SwedArcxattp2_1_M', 'SwedArcxattp2_3_F', 'SwedArcxattp2_3_M',
       'SwedArcxrepo_1_F', 'SwedArcxrepo_1_M', 'SwedArcxrepo_3_F',
       'SwedArcxrepo_3_M', 'Swedishxattp2_1_F', 'Swedishxattp2_1_M',
       'Swedishxattp2_2_F', 'Swedishxattp2_2_M', 'Swedishxrepo_1_F',
       'Swedishxrepo_1_M', 'Swedishxrepo_2_F', 'Swedishxrepo_2_M',
       'attp2xQA40_1_F', 'attp2xQA40_1_M', 'attp2xQA40_3_F',
       'attp2xQA40_3_M', 'attp2xQA42_1_F', 'attp2xQA42_1_M',
       'attp2xQA42_3_F', 'attp2xQA42_3_M', 'attp2xalrm_1_M',
       'attp2xalrm_3_F', 'attp2xalrm_3_M', 'attp2xrepo_1_F',
       'attp2xrepo_1_M', 'attp2xrepo_2_F', 'attp2xrepo_2_M',
       'attp2xrepo_3_F', 'attp2xrepo_3_M', 'attp40xQA40_3_F',
       'attp40xQA40_3_M', 'attp40xQA42_1_F', 'attp40xQA42_1_M',
       'attp40xQA42_3_F', 'attp40xQA42_3_M', 'attp40xalrm_1_M',
       'attp40xalrm_3_F', 'attp40xalrm_3_M', 'attp40xrepo_1_M',
       'attp40xrepo_2_F', 'attp40xrepo_2_M', 'attp40xrepo_3_F',
       'attp40xrepo_3_M', 'elavQFxQA40_1_F', 'elavQFxQA40_1_M',
       'elavQFxQA40_3_F', 'elavQFxQA40_3_M', 'elavQFxQA42_1_F',
       'elavQFxQA42_1_M', 'elavQFxQA42_3_F', 'elavQFxQA42_3_M',
       'elavQFxattp2_1_F', 'elavQFxattp2_1_M', 'elavQFxattp2_3_F',
       'elavQFxattp2_3_M', 'elavQFxattp40_3_F', 'elavQFxattp40_3_M',
       'attp40xQAb40_F', 'attp40xQAb40_M', 'attp40xQAb42_F',
       'attp40xQAb42_M', 'elavQFxQAb40_F', 'elavQFxQAb40_M',
       'elavQFxQAb42_F', 'elavQFxQAb42_M', 'elavQFxattp40_F',
       'elavQFxattp40_M', nan, 'London>alrmF', 'London>alrmM',
       'London>alrmvF', 'London>attp2F', 'London>attp2M',
       'London>attp2vF', 'London>elavF', 'London>elavvF',
       'London>nsybG4F', 'London>nsybG4M', 'London>nsybG4vF',
       'Swed/elavF', 'Swed>alrmF', 'Swed>alrmvF', 'Swed>attp2F',
       'Swed>attp2M', 'Swed>nsybG4F', 'Swed>nsybG4M', 'Swed>nsybG4vF',
       'SwedArc>alrmF', 'SwedArc>alrmM', 'SwedArc>attp2F',
       'SwedArc>attp2M', 'SwedArc>attp2vF', 'SwedArc>nsybG4F',
       'SwedArc>nsybG4m', 'SwedArc>nsybG4vF', 'alrm>attp2F',
       'alrm>attp2M', 'attp2>nsybG4F', 'attp2>nsybG4M', 'attp2>nsybG4vF',
       'elav>SwedArcM', 'elav>attp2F', 'elav>attp2M', 'elav>attp2vF'],
      dtype=object)

In [5]:
beam_break_data.columns[9:-4]

Index(['t0', 't1', 't2', 't3', 't4', 't5', 't6', 't7', 't8', 't9',
       ...
       't20058', 't20059', 't20060', 't20061', 't20062', 't20063', 't20064',
       't20065', 't20066', 't20067'],
      dtype='object', length=20068)

In [14]:
beam_break_data.iloc[:, 9:-4]

,t0,t1,t2,t3,t4,t5,t6,t7,t8,t9,...,t20058,t20059,t20060,t20061,t20062,t20063,t20064,t20065,t20066,t20067
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,8.0,4.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,5.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1358,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2.0,2.0,2.0,2.0,2.0,1.0,3.0,2.0,1.0,1.0
1359,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2.0,3.0,3.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0
1360,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2.0,1.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0
1361,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,2.0,3.0,0.0,1.0,1.0,0.0,1.0
1362,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [36]:
# beam_break_data_standardized = beam_break_data[['FlyID', 'Genotype_SpecSheet']]

In [ ]:
# full_standardized = standardizer(beam_break_data.iloc[:, 9:-4].values)

In [ ]:
# new_time_columns = [f't{i}' for i in range(int(20068))]
# full_beam_binned_standardized_df = pd.DataFrame(
#     data = full_standardized, 
#     columns=new_time_columns
# )
# full_beam_binned_standardized_df

,t0,t1,t2,t3,t4,t5,t6,t7,t8,t9,...,t20058,t20059,t20060,t20061,t20062,t20063,t20064,t20065,t20066,t20067
0,-0.32981,-0.32981,-0.32981,-0.32981,-0.32981,-0.32981,-0.32981,-0.32981,-0.32981,-0.32981,...,-0.329810,-0.329810,-0.329810,-0.329810,-0.329810,-0.329810,-0.329810,-0.329810,-0.329810,-0.329810
1,-0.32981,-0.32981,-0.32981,-0.32981,-0.32981,-0.32981,-0.32981,-0.32981,-0.32981,-0.32981,...,-0.329810,-0.329810,-0.329810,-0.329810,-0.329810,-0.329810,-0.329810,-0.329810,-0.329810,-0.329810
2,-0.32981,-0.32981,-0.32981,-0.32981,-0.32981,-0.32981,-0.32981,-0.32981,-0.32981,-0.32981,...,-0.329810,-0.329810,-0.329810,-0.329810,-0.329810,-0.329810,-0.329810,-0.329810,-0.329810,-0.329810
3,-0.32981,-0.32981,-0.32981,-0.32981,-0.32981,-0.32981,-0.32981,-0.32981,-0.32981,-0.32981,...,5.052851,2.361520,-0.329810,-0.329810,-0.329810,2.361520,-0.329810,-0.329810,-0.329810,-0.329810
4,-0.32981,-0.32981,-0.32981,-0.32981,-0.32981,-0.32981,-0.32981,-0.32981,-0.32981,-0.32981,...,-0.329810,3.034353,1.015855,1.015855,-0.329810,-0.329810,-0.329810,-0.329810,-0.329810,-0.329810
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1201,-0.32981,-0.32981,-0.32981,-0.32981,-0.32981,-0.32981,-0.32981,-0.32981,-0.32981,-0.32981,...,1.015855,1.015855,1.015855,1.015855,1.015855,0.343023,1.688688,1.015855,0.343023,0.343023
1202,-0.32981,-0.32981,-0.32981,-0.32981,-0.32981,-0.32981,-0.32981,-0.32981,-0.32981,-0.32981,...,1.015855,1.688688,1.688688,1.015855,1.015855,1.015855,0.343023,0.343023,1.015855,1.015855
1203,-0.32981,-0.32981,-0.32981,-0.32981,-0.32981,-0.32981,-0.32981,-0.32981,-0.32981,-0.32981,...,1.015855,0.343023,0.343023,0.343023,-0.329810,0.343023,0.343023,-0.329810,0.343023,0.343023
1204,-0.32981,-0.32981,-0.32981,-0.32981,-0.32981,-0.32981,-0.32981,-0.32981,-0.32981,-0.32981,...,0.343023,-0.329810,-0.329810,1.015855,1.688688,-0.329810,0.343023,0.343023,-0.329810,0.343023
1205,-0.32981,-0.32981,-0.32981,-0.32981,-0.32981,-0.32981,-0.32981,-0.32981,-0.32981,-0.32981,...,-0.329810,-0.329810,0.343023,-0.329810,-0.329810,-0.329810,-0.329810,-0.329810,-0.329810,-0.329810

In [ ]:
# full_beam_break_data_standardized = pd.concat([beam_break_data_standardized, full_beam_binned_standardized_df], axis=1)
# full_beam_break_data_standardized

,FlyID,Genotype_SpecSheet,t0,t1,t2,t3,t4,t5,t6,t7,...,t20058,t20059,t20060,t20061,t20062,t20063,t20064,t20065,t20066,t20067
0,M106_M118_Ch25,Londonxalrm_1_M,-0.32981,-0.32981,-0.32981,-0.32981,-0.32981,-0.32981,-0.32981,-0.32981,...,-0.329810,-0.329810,-0.329810,-0.329810,-0.32981,-0.329810,-0.32981,-0.329810,-0.329810,-0.329810
1,M106_M118_Ch26,Londonxalrm_1_M,-0.32981,-0.32981,-0.32981,-0.32981,-0.32981,-0.32981,-0.32981,-0.32981,...,-0.329810,-0.329810,-0.329810,-0.329810,-0.32981,-0.329810,-0.32981,-0.329810,-0.329810,-0.329810
2,M106_M118_Ch27,Londonxalrm_1_M,-0.32981,-0.32981,-0.32981,-0.32981,-0.32981,-0.32981,-0.32981,-0.32981,...,-0.329810,-0.329810,-0.329810,-0.329810,-0.32981,-0.329810,-0.32981,-0.329810,-0.329810,-0.329810
3,M106_M118_Ch28,Londonxalrm_1_M,-0.32981,-0.32981,-0.32981,-0.32981,-0.32981,-0.32981,-0.32981,-0.32981,...,5.052851,2.361520,-0.329810,-0.329810,-0.32981,2.361520,-0.32981,-0.329810,-0.329810,-0.329810
4,M106_M118_Ch29,Londonxalrm_1_M,-0.32981,-0.32981,-0.32981,-0.32981,-0.32981,-0.32981,-0.32981,-0.32981,...,-0.329810,3.034353,1.015855,1.015855,-0.32981,-0.329810,-0.32981,-0.329810,-0.329810,-0.329810
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
847,NaN,NaN,-0.32981,-0.32981,-0.32981,-0.32981,-0.32981,-0.32981,-0.32981,-0.32981,...,-0.329810,-0.329810,-0.329810,-0.329810,-0.32981,-0.329810,-0.32981,-0.329810,-0.329810,-0.329810
848,NaN,NaN,-0.32981,-0.32981,-0.32981,-0.32981,-0.32981,-0.32981,-0.32981,-0.32981,...,-0.329810,-0.329810,-0.329810,1.688688,-0.32981,0.343023,-0.32981,0.343023,1.688688,1.688688
849,NaN,NaN,-0.32981,-0.32981,-0.32981,-0.32981,-0.32981,-0.32981,-0.32981,-0.32981,...,-0.329810,-0.329810,-0.329810,-0.329810,-0.32981,-0.329810,-0.32981,-0.329810,-0.329810,-0.329810
850,NaN,NaN,-0.32981,-0.32981,-0.32981,-0.32981,-0.32981,-0.32981,-0.32981,-0.32981,...,-0.329810,-0.329810,-0.329810,-0.329810,-0.32981,-0.329810,-0.32981,-0.329810,-0.329810,-0.329810
851,NaN,NaN,-0.32981,-0.32981,-0.32981,-0.32981,-0.32981,-0.32981,-0.32981,-0.32981,...,3.034353,4.380018,-0.329810,-0.329810,-0.32981,-0.329810,-0.32981,-0.329810,-0.329810,-0.329810

In [ ]:
# full_beam_break_data_standardized.iloc[:, 2:]

,t0,t1,t2,t3,t4,t5,t6,t7,t8,t9,...,t20058,t20059,t20060,t20061,t20062,t20063,t20064,t20065,t20066,t20067
0,-0.317396,-0.317396,-0.317396,-0.317396,-0.317396,-0.317396,-0.317396,-0.317396,-0.317396,-0.317396,...,-0.317396,-0.317396,-0.317396,-0.317396,-0.317396,-0.317396,-0.317396,-0.317396,-0.317396,-0.317396
1,-0.317396,-0.317396,-0.317396,-0.317396,-0.317396,-0.317396,-0.317396,-0.317396,-0.317396,-0.317396,...,-0.317396,-0.317396,-0.317396,-0.317396,-0.317396,-0.317396,-0.317396,-0.317396,-0.317396,-0.317396
2,-0.317396,-0.317396,-0.317396,-0.317396,-0.317396,-0.317396,-0.317396,-0.317396,-0.317396,-0.317396,...,-0.317396,-0.317396,-0.317396,-0.317396,-0.317396,-0.317396,-0.317396,-0.317396,-0.317396,-0.317396
3,-0.317396,-0.317396,-0.317396,-0.317396,-0.317396,-0.317396,-0.317396,-0.317396,-0.317396,-0.317396,...,4.776551,2.229577,-0.317396,-0.317396,-0.317396,2.229577,-0.317396,-0.317396,-0.317396,-0.317396
4,-0.317396,-0.317396,-0.317396,-0.317396,-0.317396,-0.317396,-0.317396,-0.317396,-0.317396,-0.317396,...,-0.317396,2.866321,0.956091,0.956091,-0.317396,-0.317396,-0.317396,-0.317396,-0.317396,-0.317396
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1358,-0.317396,-0.317396,-0.317396,-0.317396,-0.317396,-0.317396,-0.317396,-0.317396,-0.317396,-0.317396,...,0.956091,0.956091,0.956091,0.956091,0.956091,0.319347,1.592834,0.956091,0.319347,0.319347
1359,-0.317396,-0.317396,-0.317396,-0.317396,-0.317396,-0.317396,-0.317396,-0.317396,-0.317396,-0.317396,...,0.956091,1.592834,1.592834,0.956091,0.956091,0.956091,0.319347,0.319347,0.956091,0.956091
1360,-0.317396,-0.317396,-0.317396,-0.317396,-0.317396,-0.317396,-0.317396,-0.317396,-0.317396,-0.317396,...,0.956091,0.319347,0.319347,0.319347,-0.317396,0.319347,0.319347,-0.317396,0.319347,0.319347
1361,-0.317396,-0.317396,-0.317396,-0.317396,-0.317396,-0.317396,-0.317396,-0.317396,-0.317396,-0.317396,...,0.319347,-0.317396,-0.317396,0.956091,1.592834,-0.317396,0.319347,0.319347,-0.317396,0.319347
1362,-0.317396,-0.317396,-0.317396,-0.317396,-0.317396,-0.317396,-0.317396,-0.317396,-0.317396,-0.317396,...,-0.317396,-0.317396,0.319347,-0.317396,-0.317396,-0.317396,-0.317396,-0.317396,-0.317396,-0.317396

In [ ]:
# full_beam_break_data_standardized.to_csv('/home/rachel/Desktop/mm-vae_ext2/data/full_beam_break_standardized.csv', index=False)

In [42]:
beam_break_data_binned = beam_break_data[['FlyID', 'Genotype_SpecSheet']]
beam_break_data_binned

               FlyID Genotype_SpecSheet
0     M106_M118_Ch25    Londonxalrm_1_M
1     M106_M118_Ch26    Londonxalrm_1_M
2     M106_M118_Ch27    Londonxalrm_1_M
3     M106_M118_Ch28    Londonxalrm_1_M
4     M106_M118_Ch29    Londonxalrm_1_M
...              ...                ...
1201    M96_M48_Ch28       elav>attp2vF
1202    M96_M48_Ch29       elav>attp2vF
1203    M96_M48_Ch30       elav>attp2vF
1204    M96_M48_Ch31       elav>attp2vF
1205    M96_M48_Ch32       elav>attp2vF

[1206 rows x 2 columns]

In [43]:
beam_break_data_binned_length = beam_break_data.iloc[:, 9:-4].shape[1] / 4
beam_break_data_binned_length

5017.0

In [39]:
beam_break_data.iloc[:, 9:-4].values

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 1., 1.],
       [0., 0., 0., ..., 1., 0., 1.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [44]:
beam_data = beam_break_data.iloc[:, 9:-4].values
beam_bins = beam_data.reshape(beam_break_data.shape[0], int(beam_break_data_binned_length), 4)
beam_bins.shape

(1206, 5017, 4)

In [45]:
beam_binned = beam_bins.sum(axis=2)
beam_binned.shape

(1206, 5017)

In [46]:
new_time_columns = [f't{i}' for i in range(int(beam_break_data_binned_length))]
beam_binned_df = pd.DataFrame(
    data = beam_binned, 
    columns=new_time_columns
)
beam_binned_df

,t0,t1,t2,t3,t4,t5,t6,t7,t8,t9,...,t5007,t5008,t5009,t5010,t5011,t5012,t5013,t5014,t5015,t5016
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,5.0,16.0,7.0,28.0,1.0,3.0,6.0,27.0,4.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,3.0,8.0,7.0,4.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1201,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,6.0,8.0,6.0,9.0,8.0,8.0,7.0,6.0,7.0,7.0
1202,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,10.0,9.0,8.0,6.0,8.0,10.0,8.0,10.0,9.0,6.0
1203,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4.0,4.0,4.0,2.0,0.0,0.0,0.0,3.0,3.0,3.0
1204,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,6.0,3.0,3.0,9.0,3.0,4.0,10.0,1.0,5.0,3.0
1205,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,7.0,7.0,4.0,2.0,6.0,3.0,7.0,2.0,1.0,0.0

In [47]:
final_beam_break_binned = pd.concat([beam_break_data_binned, beam_binned_df], axis=1)
final_beam_break_binned

,FlyID,Genotype_SpecSheet,t0,t1,t2,t3,t4,t5,t6,t7,...,t5007,t5008,t5009,t5010,t5011,t5012,t5013,t5014,t5015,t5016
0,M106_M118_Ch25,Londonxalrm_1_M,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,M106_M118_Ch26,Londonxalrm_1_M,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,M106_M118_Ch27,Londonxalrm_1_M,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,M106_M118_Ch28,Londonxalrm_1_M,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,5.0,16.0,7.0,28.0,1.0,3.0,6.0,27.0,4.0,0.0
4,M106_M118_Ch29,Londonxalrm_1_M,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,3.0,8.0,7.0,4.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1201,M96_M48_Ch28,elav>attp2vF,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,6.0,8.0,6.0,9.0,8.0,8.0,7.0,6.0,7.0,7.0
1202,M96_M48_Ch29,elav>attp2vF,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,10.0,9.0,8.0,6.0,8.0,10.0,8.0,10.0,9.0,6.0
1203,M96_M48_Ch30,elav>attp2vF,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4.0,4.0,4.0,2.0,0.0,0.0,0.0,3.0,3.0,3.0
1204,M96_M48_Ch31,elav>attp2vF,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,6.0,3.0,3.0,9.0,3.0,4.0,10.0,1.0,5.0,3.0
1205,M96_M48_Ch32,elav>attp2vF,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,7.0,7.0,4.0,2.0,6.0,3.0,7.0,2.0,1.0,0.0

In [48]:
final_beam_break_binned.to_csv('/home/rachel/Desktop/mm-vae_ext2/data/raw_beam_break_binned.csv', index=False)

In [49]:
raw_beam_break_binned = pd.read_csv('/home/rachel/Desktop/mm-vae_ext2/data/raw_beam_break_binned.csv')
raw_beam_break_binned

,FlyID,Genotype_SpecSheet,t0,t1,t2,t3,t4,t5,t6,t7,...,t5007,t5008,t5009,t5010,t5011,t5012,t5013,t5014,t5015,t5016
0,M106_M118_Ch25,Londonxalrm_1_M,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,M106_M118_Ch26,Londonxalrm_1_M,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,M106_M118_Ch27,Londonxalrm_1_M,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,M106_M118_Ch28,Londonxalrm_1_M,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,5.0,16.0,7.0,28.0,1.0,3.0,6.0,27.0,4.0,0.0
4,M106_M118_Ch29,Londonxalrm_1_M,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,3.0,8.0,7.0,4.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1201,M96_M48_Ch28,elav>attp2vF,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,6.0,8.0,6.0,9.0,8.0,8.0,7.0,6.0,7.0,7.0
1202,M96_M48_Ch29,elav>attp2vF,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,10.0,9.0,8.0,6.0,8.0,10.0,8.0,10.0,9.0,6.0
1203,M96_M48_Ch30,elav>attp2vF,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4.0,4.0,4.0,2.0,0.0,0.0,0.0,3.0,3.0,3.0
1204,M96_M48_Ch31,elav>attp2vF,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,6.0,3.0,3.0,9.0,3.0,4.0,10.0,1.0,5.0,3.0
1205,M96_M48_Ch32,elav>attp2vF,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,7.0,7.0,4.0,2.0,6.0,3.0,7.0,2.0,1.0,0.0

In [50]:
raw_beam_break_binned.iloc[:, 2:]

,t0,t1,t2,t3,t4,t5,t6,t7,t8,t9,...,t5007,t5008,t5009,t5010,t5011,t5012,t5013,t5014,t5015,t5016
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,5.0,16.0,7.0,28.0,1.0,3.0,6.0,27.0,4.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,3.0,8.0,7.0,4.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1201,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,6.0,8.0,6.0,9.0,8.0,8.0,7.0,6.0,7.0,7.0
1202,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,10.0,9.0,8.0,6.0,8.0,10.0,8.0,10.0,9.0,6.0
1203,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4.0,4.0,4.0,2.0,0.0,0.0,0.0,3.0,3.0,3.0
1204,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,6.0,3.0,3.0,9.0,3.0,4.0,10.0,1.0,5.0,3.0
1205,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,7.0,7.0,4.0,2.0,6.0,3.0,7.0,2.0,1.0,0.0

In [51]:
beam_binned.shape

(1206, 5017)

In [52]:
beam_binned_standardized = standardizer(beam_binned)
beam_binned_standardized

array([[-0.44861317, -0.44861317, -0.44861317, ..., -0.44861317,
        -0.44861317, -0.44861317],
       [-0.44861317, -0.44861317, -0.44861317, ..., -0.44861317,
        -0.44861317, -0.44861317],
       [-0.44861317, -0.44861317, -0.44861317, ..., -0.44861317,
        -0.44861317, -0.44861317],
       ...,
       [-0.44861317, -0.44861317, -0.44861317, ...,  0.23778583,
         0.23778583,  0.23778583],
       [-0.44861317, -0.44861317, -0.44861317, ..., -0.2198135 ,
         0.69538517,  0.23778583],
       [-0.44861317, -0.44861317, -0.44861317, ...,  0.00898617,
        -0.2198135 , -0.44861317]])

In [53]:
new_time_columns = [f't{i}' for i in range(int(beam_break_data_binned_length))]
beam_binned_standardized_df = pd.DataFrame(
    data = beam_binned_standardized, 
    columns=new_time_columns
)
beam_binned_standardized_df

,t0,t1,t2,t3,t4,t5,t6,t7,t8,t9,...,t5007,t5008,t5009,t5010,t5011,t5012,t5013,t5014,t5015,t5016
0,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,...,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613
1,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,...,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613
2,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,...,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613
3,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,...,0.695385,3.212182,1.152985,5.957778,-0.219814,0.237786,0.924185,5.728978,0.466586,-0.448613
4,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,...,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,0.237786,1.381784,1.152985,0.466586,-0.448613
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1201,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,...,0.924185,1.381784,0.924185,1.610584,1.381784,1.381784,1.152985,0.924185,1.152985,1.152985
1202,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,...,1.839384,1.610584,1.381784,0.924185,1.381784,1.839384,1.381784,1.839384,1.610584,0.924185
1203,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,...,0.466586,0.466586,0.466586,0.008986,-0.448613,-0.448613,-0.448613,0.237786,0.237786,0.237786
1204,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,...,0.924185,0.237786,0.237786,1.610584,0.237786,0.466586,1.839384,-0.219814,0.695385,0.237786
1205,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,...,1.152985,1.152985,0.466586,0.008986,0.924185,0.237786,1.152985,0.008986,-0.219814,-0.448613

In [54]:
final_beam_break_standardized_binned = pd.concat([beam_break_data_binned, beam_binned_standardized_df], axis=1)
final_beam_break_standardized_binned

,FlyID,Genotype_SpecSheet,t0,t1,t2,t3,t4,t5,t6,t7,...,t5007,t5008,t5009,t5010,t5011,t5012,t5013,t5014,t5015,t5016
0,M106_M118_Ch25,Londonxalrm_1_M,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,...,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613
1,M106_M118_Ch26,Londonxalrm_1_M,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,...,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613
2,M106_M118_Ch27,Londonxalrm_1_M,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,...,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613
3,M106_M118_Ch28,Londonxalrm_1_M,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,...,0.695385,3.212182,1.152985,5.957778,-0.219814,0.237786,0.924185,5.728978,0.466586,-0.448613
4,M106_M118_Ch29,Londonxalrm_1_M,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,...,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,0.237786,1.381784,1.152985,0.466586,-0.448613
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1201,M96_M48_Ch28,elav>attp2vF,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,...,0.924185,1.381784,0.924185,1.610584,1.381784,1.381784,1.152985,0.924185,1.152985,1.152985
1202,M96_M48_Ch29,elav>attp2vF,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,...,1.839384,1.610584,1.381784,0.924185,1.381784,1.839384,1.381784,1.839384,1.610584,0.924185
1203,M96_M48_Ch30,elav>attp2vF,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,...,0.466586,0.466586,0.466586,0.008986,-0.448613,-0.448613,-0.448613,0.237786,0.237786,0.237786
1204,M96_M48_Ch31,elav>attp2vF,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,...,0.924185,0.237786,0.237786,1.610584,0.237786,0.466586,1.839384,-0.219814,0.695385,0.237786
1205,M96_M48_Ch32,elav>attp2vF,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,-0.448613,...,1.152985,1.152985,0.466586,0.008986,0.924185,0.237786,1.152985,0.008986,-0.219814,-0.448613

In [55]:
final_beam_break_binned.to_csv('/home/rachel/Desktop/mm-vae_ext2/data/raw_beam_break_standardized_binned.csv', index=False)

In [ ]:
batch_size = 128
train_set = DataBuilder(raw_beam_break_binned)
test_set = DataBuilder(raw_beam_break_binned)
train_loader = DataLoader(train_set, batch_size=batch_size, shuffle=True)
test_loader = DataLoader(test_set, batch_size=len(test_set), shuffle=True)

In [ ]:
data, fly_id, genotype = next(iter(train_loader))
print(data.shape)
print(len(fly_id))
print(len(genotype))

torch.Size([128, 5017])
128
128

In [ ]:
data

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 1., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

In [ ]:
fly_id

('M106_M13_Ch5',
 'M153_M28_Ch5',
 'M96_M24_Ch10',
 'M106_M14_Ch17',
 'M106_M111_Ch31',
 'M153_M28_Ch1',
 'M106_M22_Ch8',
 'M106_M117_Ch14',
 'M106_M22_Ch11',
 'M96_M9_Ch24',
 'M96_M48_Ch6',
 'M106_M111_Ch14',
 'M106_M14_Ch21',
 'M153_M30_Ch25',
 'M96_M25_Ch18',
 'M153_M29_Ch6',
 'M96_M79_Ch25',
 'M96_M10_Ch32',
 'M96_M9_Ch23',
 'M119_M48_Ch29',
 'M106_M15_Ch26',
 'M106_M24_Ch24',
 'M96_M29_Ch11',
 'M106_M115_Ch23',
 'M106_M24_Ch1',
 'M106_M14_Ch31',
 'M106_M120_Ch10',
 'M96_M56_Ch17',
 'M96_M29_Ch3',
 'M96_M29_Ch19',
 'M96_M9_Ch7',
 'M96_M9_Ch4',
 'M106_M116_Ch20',
 'M106_M13_Ch21',
 'M153_M28_Ch30',
 'M96_M10_Ch12',
 'M96_M54_Ch25',
 'M106_M22_Ch16',
 'M106_M24_Ch17',
 'M96_M76_Ch9',
 'M96_M48_Ch10',
 'M106_M4_Ch10',
 'M106_M15_Ch32',
 'M119_M49_Ch8',
 'M106_M111_Ch20',
 'M153_M30_Ch21',
 'M106_M16_Ch31',
 'M153_M30_Ch29',
 'M106_M7_Ch18',
 'M96_M29_Ch20',
 'M106_M4_Ch31',
 'M119_M48_Ch16',
 'M96_M9_Ch13',
 'M153_M27_Ch9',
 'M96_M10_Ch20',
 'M106_M22_Ch9',
 'M96_M79_Ch24',
 'M106_M30_Ch17',
 'M96_M76_Ch32',
 'M96_M80_Ch6',
 'M106_M119_Ch13',
 'M106_M30_Ch26',
 'M106_M25_Ch10',
 'M106_M14_Ch29',
 'M96_M56_Ch21',
 'M96_M79_Ch20',
 'M106_M115_Ch12',
 'M96_M50_Ch24',
 'M96_M8_Ch21',
 'M96_M24_Ch4',
 'M106_M16_Ch10',
 'M96_M9_Ch27',
 'M96_M48_Ch28',
 'M106_M25_Ch20',
 'M106_M22_Ch28',
 'M106_M120_Ch8',
 'M106_M33_Ch25',
 'M106_M25_Ch3',
 'M106_M13_Ch22',
 'M106_M120_Ch21',
 'M106_M111_Ch7',
 'M96_M57_Ch27',
 'M119_M49_Ch11',
 'M96_M49_Ch15',
 'M106_M24_Ch9',
 'M153_M27_Ch32',
 'M96_M82_Ch18',
 'M106_M112_Ch2',
 'M96_M29_Ch30',
 'M96_M24_Ch7',
 'M96_M8_Ch27',
 'M106_M16_Ch22',
 'M96_M8_Ch29',
 'M96_M49_Ch5',
 'M106_M24_Ch25',
 'M106_M111_Ch1',
 'M96_M50_Ch5',
 'M106_M7_Ch2',
 'M153_M27_Ch2',
 'M96_M48_Ch31',
 'M153_M27_Ch25',
 'M96_M8_Ch14',
 'M153_M30_Ch20',
 'M106_M111_Ch18',
 'M96_M49_Ch2',
 'M153_M27_Ch28',
 'M106_M119_Ch21',
 'M96_M8_Ch17',
 'M106_M7_Ch9',
 'M119_M50_Ch29',
 'M96_M48_Ch20',
 'M106_M120_Ch17',
 'M106_M14_Ch20',
 'M106_M112_Ch27',
 'M106_M119_Ch9',
 'M153_M29_Ch32',
 'M106_M7_Ch20',
 'M96_M80_Ch27',
 'M96_M29_Ch10',
 'M96_M48_Ch5',
 'M96_M29_Ch2',
 'M106_M118_Ch16',
 'M96_M10_Ch24',
 'M96_M8_Ch12',
 'M96_M82_Ch11',
 'M96_M9_Ch8',
 'M96_M79_Ch7',
 'M96_M24_Ch28')

In [ ]:
genotype

('elavQFxQA40_1_M',
 nan,
 'Swed>nsybG4M',
 'Swedishxattp2_1_M',
 'attp40xQA42_1_F',
 nan,
 'attp40xrepo_3_M',
 'Londonxrepo_2_F',
 'attp40xrepo_3_M',
 'SwedArc>nsybG4vF',
 'elav>SwedArcM',
 'attp40xQA42_3_F',
 'Swedishxattp2_1_M',
 nan,
 'attp2>nsybG4vF',
 nan,
 'SwedArc>attp2vF',
 'SwedArc>nsybG4F',
 'SwedArc>nsybG4vF',
 'attp40xQAb42_F',
 'SwedArcxrepo_1_F',
 'Swedishxrepo_1_F',
 'attp2>nsybG4M',
 'Londonxattp40_3_M',
 'Swedishxrepo_2_M',
 'Swedishxattp2_1_F',
 'attp2xrepo_1_F',
 'alrm>attp2F',
 'attp2>nsybG4M',
 'attp2>nsybG4F',
 'London>nsybG4vF',
 'London>nsybG4vF',
 'Londonxrepo_3_M',
 'elavQFxQA42_3_M',
 nan,
 'SwedArc>nsybG4m',
 'Swed>alrmF',
 'attp40xrepo_3_F',
 'Swedishxrepo_1_M',
 'London>attp2M',
 'elav>SwedArcM',
 'elavQFxattp2_3_F',
 'SwedArcxrepo_1_F',
 'attp40xQAb42_M',
 'attp40xQA42_1_M',
 nan,
 'attp40xalrm_1_M',
 nan,
 'elavQFxQA40_3_M',
 'attp2>nsybG4F',
 'elavQFxattp2_1_F',
 'elavQFxQAb42_M',
 'London>nsybG4vF',
 nan,
 'SwedArc>nsybG4F',
 'attp40xrepo_3_M',
 'SwedArc>attp2vF',
 'attp2xQA42_3_M',
 'London>attp2F',
 'SwedArc>attp2M',
 'attp2xrepo_3_F',
 'attp2xQA42_3_F',
 'SwedArcxattp2_3_F',
 'Swedishxattp2_1_F',
 'alrm>attp2F',
 'SwedArc>attp2vF',
 'Londonxattp2_1_F',
 'London>alrmF',
 'London>nsybG4F',
 'Swed>nsybG4M',
 'attp40xrepo_1_M',
 'SwedArc>nsybG4vF',
 'elav>attp2vF',
 'SwedArcxattp2_1_M',
 'attp40xrepo_2_M',
 'attp2xrepo_1_M',
 'attp40xQA40_3_F',
 'SwedArcxattp2_3_M',
 'elavQFxQA42_3_M',
 'attp2xalrm_3_M',
 'attp40xQA42_3_M',
 'Swed/elavF',
 'attp40xQAb42_M',
 'SwedArc>alrmM',
 'Swedishxrepo_2_F',
 nan,
 'Swed>attp2F',
 'Londonxattp2_3_M',
 'attp2>nsybG4F',
 'Swed>nsybG4M',
 'London>nsybG4F',
 'attp40xalrm_3_F',
 'London>nsybG4F',
 'SwedArc>alrmM',
 'Swedishxrepo_1_F',
 'attp40xQA42_3_M',
 'London>alrmM',
 'elavQFxattp40_3_M',
 nan,
 'elav>attp2vF',
 nan,
 'London>nsybG4M',
 nan,
 'attp40xQA42_1_M',
 'SwedArc>alrmM',
 nan,
 'attp2xrepo_2_M',
 'London>nsybG4F',
 'elavQFxattp40_3_F',
 'attp40xQAb40_M',
 'elav>attp2vF',
 'attp2xalrm_3_M',
 'Swedishxattp2_1_M',
 'Londonxattp2_2_F',
 'attp2xrepo_3_F',
 nan,
 'elavQFxQA40_3_M',
 'SwedArc>attp2F',
 'attp2>nsybG4M',
 'elav>SwedArcM',
 'attp2>nsybG4M',
 'Londonxalrm_2_M',
 'SwedArc>nsybG4F',
 'London>nsybG4M',
 'Swed>attp2M',
 'London>nsybG4vF',
 'London>attp2vF',
 'Swed>nsybG4F')

In [ ]:
data_test, fly_id_test, genotype_test = next(iter(test_loader))
print(data_test.shape)
print(len(fly_id_test))
print(len(genotype_test))

torch.Size([1363, 5017])
1363
1363