In [7]:
import numpy as np
import pandas as pd

In [3]:
data_cfc = pd.read_csv('/home/rachel/Desktop/mm-vae data/caloric_restriction_DO_mice/nature_filtered_nonan_cfc.csv')
data_cfc

,MouseID,Generation,SurvDays,Y1A_BW_BW,Y2A_BW_BW,Y3A_BW_BW,Y1_Glu.F_Glucose,Y2_Glu.F_Glucose,Y3_Glu.F_Glucose,Y1_Echo_BPM,...,Y2_Wheel_AvgDistLFC,Y3_Wheel_AvgDistLFC,Y1A_Grip_All,Y2A_Grip_All,Y3A_Grip_All,Y1A_Frailty_FrailtyAdj,Y2A_Frailty_FrailtyAdj,Y3A_Frailty_FrailtyAdj,Diet_num,Diet
0,DO-40-2162,28,1611,24.787142,26.993230,23.645309,164.713839,134.572768,74.479328,499.174601,...,1.716889,4.448401,89.962669,168.389945,179.558615,0.032865,0.133616,0.159587,1,40
1,DO-40-2179,28,1557,30.432753,23.594599,23.529931,161.043852,71.901384,69.226421,495.841743,...,0.348339,0.747802,291.910043,181.741358,208.833723,0.183285,0.231782,0.235033,1,40
2,DO-40-2181,28,1533,20.747600,19.072890,20.528352,161.043852,93.048894,60.575167,520.949018,...,0.204999,0.192929,221.922043,204.078358,158.799723,0.069442,0.231782,0.197085,1,40
3,DO-40-2187,28,1520,25.977819,29.254446,30.242503,127.747193,85.358891,71.148922,466.210754,...,1.146192,0.924488,145.679543,223.139358,208.833223,0.106295,0.174654,0.216059,1,40
4,DO-40-2099,26,1638,24.242912,23.626717,22.912834,166.520150,72.692867,59.960123,464.789558,...,1.776962,2.179152,261.760471,173.953709,153.357082,0.110173,0.155822,0.285573,1,40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499,DO-2D-4007,22,771,40.141463,46.980545,67.590983,112.556159,165.312618,261.476515,554.545551,...,1.715710,-2.736010,206.457287,161.382753,58.352082,0.301015,0.209083,0.555556,3,2D
500,DO-1D-3030,22,748,24.315156,29.916707,67.590983,139.326564,136.439061,261.476515,544.317015,...,0.934841,-2.736010,223.713073,138.051810,58.352082,0.301015,0.082493,0.555556,4,1D
501,DO-20-1021,22,738,30.809768,38.120260,67.590983,168.911742,152.502965,261.476515,542.558402,...,1.218057,-2.736010,194.721573,162.770810,58.352082,0.301015,0.224366,0.555556,2,20
502,DO-AL-0002,22,755,30.261862,48.841393,67.590983,139.018370,125.113095,261.476515,477.144237,...,3.236146,-2.736010,139.520787,117.007253,58.352082,0.301015,0.277963,0.555556,5,AL
503,DO-40-2006,22,750,22.588584,19.184004,67.590983,114.025857,60.709314,261.476515,472.837574,...,-1.894866,-2.736010,166.380787,150.065753,58.352082,0.301015,0.202068,0.555556,1,40

In [4]:
cfc_data = pd.read_csv('/home/rachel/Desktop/mm-vae data/caloric_restriction_DO_mice/cfc_data_filtered.csv')
cfc_data

    Diet    Mouse.ID  CFC.24mo.Average
0     1D  DO-1D-3001              0.84
1     1D  DO-1D-3003             83.69
2     1D  DO-1D-3010             36.71
3     1D  DO-1D-3011             21.96
4     1D  DO-1D-3013              6.93
..   ...         ...               ...
499   AL  DO-AL-0184             25.56
500   AL  DO-AL-0185             13.73
501   AL  DO-AL-0186             20.44
502   AL  DO-AL-0188             18.31
503   AL  DO-AL-0191             24.71

[504 rows x 3 columns]

In [5]:
data_cfc_with_cfc = pd.merge(data_cfc, cfc_data, left_on='MouseID', right_on='Mouse.ID')
data_cfc_with_cfc

,MouseID,Generation,SurvDays,Y1A_BW_BW,Y2A_BW_BW,Y3A_BW_BW,Y1_Glu.F_Glucose,Y2_Glu.F_Glucose,Y3_Glu.F_Glucose,Y1_Echo_BPM,...,Y2A_Grip_All,Y3A_Grip_All,Y1A_Frailty_FrailtyAdj,Y2A_Frailty_FrailtyAdj,Y3A_Frailty_FrailtyAdj,Diet_num,Diet_x,Diet_y,Mouse.ID,CFC.24mo.Average
0,DO-40-2162,28,1611,24.787142,26.993230,23.645309,164.713839,134.572768,74.479328,499.174601,...,168.389945,179.558615,0.032865,0.133616,0.159587,1,40,40,DO-40-2162,3.78
1,DO-40-2179,28,1557,30.432753,23.594599,23.529931,161.043852,71.901384,69.226421,495.841743,...,181.741358,208.833723,0.183285,0.231782,0.235033,1,40,40,DO-40-2179,26.71
2,DO-40-2181,28,1533,20.747600,19.072890,20.528352,161.043852,93.048894,60.575167,520.949018,...,204.078358,158.799723,0.069442,0.231782,0.197085,1,40,40,DO-40-2181,27.02
3,DO-40-2187,28,1520,25.977819,29.254446,30.242503,127.747193,85.358891,71.148922,466.210754,...,223.139358,208.833223,0.106295,0.174654,0.216059,1,40,40,DO-40-2187,50.40
4,DO-40-2099,26,1638,24.242912,23.626717,22.912834,166.520150,72.692867,59.960123,464.789558,...,173.953709,153.357082,0.110173,0.155822,0.285573,1,40,40,DO-40-2099,34.18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499,DO-2D-4007,22,771,40.141463,46.980545,67.590983,112.556159,165.312618,261.476515,554.545551,...,161.382753,58.352082,0.301015,0.209083,0.555556,3,2D,2D,DO-2D-4007,23.69
500,DO-1D-3030,22,748,24.315156,29.916707,67.590983,139.326564,136.439061,261.476515,544.317015,...,138.051810,58.352082,0.301015,0.082493,0.555556,4,1D,1D,DO-1D-3030,29.78
501,DO-20-1021,22,738,30.809768,38.120260,67.590983,168.911742,152.502965,261.476515,542.558402,...,162.770810,58.352082,0.301015,0.224366,0.555556,2,20,20,DO-20-1021,18.22
502,DO-AL-0002,22,755,30.261862,48.841393,67.590983,139.018370,125.113095,261.476515,477.144237,...,117.007253,58.352082,0.301015,0.277963,0.555556,5,AL,AL,DO-AL-0002,57.42
503,DO-40-2006,22,750,22.588584,19.184004,67.590983,114.025857,60.709314,261.476515,472.837574,...,150.065753,58.352082,0.301015,0.202068,0.555556,1,40,40,DO-40-2006,12.58

In [6]:
bin_edges = [0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
bin_labels = range(10)
data_cfc_with_cfc['cfc_bin'] = pd.cut(data_cfc_with_cfc['CFC.24mo.Average'], bins=bin_edges, labels=bin_labels, right=True, include_lowest=True)
data_cfc_with_cfc

,MouseID,Generation,SurvDays,Y1A_BW_BW,Y2A_BW_BW,Y3A_BW_BW,Y1_Glu.F_Glucose,Y2_Glu.F_Glucose,Y3_Glu.F_Glucose,Y1_Echo_BPM,...,Y3A_Grip_All,Y1A_Frailty_FrailtyAdj,Y2A_Frailty_FrailtyAdj,Y3A_Frailty_FrailtyAdj,Diet_num,Diet_x,Diet_y,Mouse.ID,CFC.24mo.Average,cfc_bin
0,DO-40-2162,28,1611,24.787142,26.993230,23.645309,164.713839,134.572768,74.479328,499.174601,...,179.558615,0.032865,0.133616,0.159587,1,40,40,DO-40-2162,3.78,0
1,DO-40-2179,28,1557,30.432753,23.594599,23.529931,161.043852,71.901384,69.226421,495.841743,...,208.833723,0.183285,0.231782,0.235033,1,40,40,DO-40-2179,26.71,2
2,DO-40-2181,28,1533,20.747600,19.072890,20.528352,161.043852,93.048894,60.575167,520.949018,...,158.799723,0.069442,0.231782,0.197085,1,40,40,DO-40-2181,27.02,2
3,DO-40-2187,28,1520,25.977819,29.254446,30.242503,127.747193,85.358891,71.148922,466.210754,...,208.833223,0.106295,0.174654,0.216059,1,40,40,DO-40-2187,50.40,5
4,DO-40-2099,26,1638,24.242912,23.626717,22.912834,166.520150,72.692867,59.960123,464.789558,...,153.357082,0.110173,0.155822,0.285573,1,40,40,DO-40-2099,34.18,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499,DO-2D-4007,22,771,40.141463,46.980545,67.590983,112.556159,165.312618,261.476515,554.545551,...,58.352082,0.301015,0.209083,0.555556,3,2D,2D,DO-2D-4007,23.69,2
500,DO-1D-3030,22,748,24.315156,29.916707,67.590983,139.326564,136.439061,261.476515,544.317015,...,58.352082,0.301015,0.082493,0.555556,4,1D,1D,DO-1D-3030,29.78,2
501,DO-20-1021,22,738,30.809768,38.120260,67.590983,168.911742,152.502965,261.476515,542.558402,...,58.352082,0.301015,0.224366,0.555556,2,20,20,DO-20-1021,18.22,1
502,DO-AL-0002,22,755,30.261862,48.841393,67.590983,139.018370,125.113095,261.476515,477.144237,...,58.352082,0.301015,0.277963,0.555556,5,AL,AL,DO-AL-0002,57.42,5
503,DO-40-2006,22,750,22.588584,19.184004,67.590983,114.025857,60.709314,261.476515,472.837574,...,58.352082,0.301015,0.202068,0.555556,1,40,40,DO-40-2006,12.58,1

In [8]:
def standardize(input_array):
    mean = np.nanmean(input_array)
    std = np.nanstd(input_array)
    return (input_array - mean) / std

In [10]:
data_cfc_with_cfc.iloc[:, 3:-6] = standardize(data_cfc_with_cfc.iloc[:, 3:-6])
data_cfc_with_cfc

,MouseID,Generation,SurvDays,Y1A_BW_BW,Y2A_BW_BW,Y3A_BW_BW,Y1_Glu.F_Glucose,Y2_Glu.F_Glucose,Y3_Glu.F_Glucose,Y1_Echo_BPM,...,Y3A_Grip_All,Y1A_Frailty_FrailtyAdj,Y2A_Frailty_FrailtyAdj,Y3A_Frailty_FrailtyAdj,Diet_num,Diet_x,Diet_y,Mouse.ID,CFC.24mo.Average,cfc_bin
0,DO-40-2162,28,1611,-0.299075,-0.298795,-0.299221,-0.281284,-0.285116,-0.292757,-0.238758,...,-0.279397,-0.302223,-0.302210,-0.302207,1,40,40,DO-40-2162,3.78,0
1,DO-40-2179,28,1557,-0.298358,-0.299227,-0.299235,-0.281751,-0.293085,-0.293425,-0.239182,...,-0.275674,-0.302204,-0.302197,-0.302197,1,40,40,DO-40-2179,26.71,2
2,DO-40-2181,28,1533,-0.299589,-0.299802,-0.299617,-0.281751,-0.290396,-0.294525,-0.235990,...,-0.282036,-0.302218,-0.302197,-0.302202,1,40,40,DO-40-2181,27.02,2
3,DO-40-2187,28,1520,-0.298924,-0.298507,-0.298382,-0.285984,-0.291374,-0.293181,-0.242950,...,-0.275674,-0.302213,-0.302205,-0.302199,1,40,40,DO-40-2187,50.40,5
4,DO-40-2099,26,1638,-0.299145,-0.299223,-0.299314,-0.281054,-0.292984,-0.294603,-0.243130,...,-0.282728,-0.302213,-0.302207,-0.302191,1,40,40,DO-40-2099,34.18,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499,DO-2D-4007,22,771,-0.297123,-0.296254,-0.293633,-0.287916,-0.281208,-0.268981,-0.231718,...,-0.294808,-0.302189,-0.302200,-0.302156,3,2D,2D,DO-2D-4007,23.69,2
500,DO-1D-3030,22,748,-0.299135,-0.298423,-0.293633,-0.284512,-0.284879,-0.268981,-0.233019,...,-0.294808,-0.302189,-0.302216,-0.302156,4,1D,1D,DO-1D-3030,29.78,2
501,DO-20-1021,22,738,-0.298310,-0.297380,-0.293633,-0.280750,-0.282837,-0.268981,-0.233242,...,-0.294808,-0.302189,-0.302198,-0.302156,2,20,20,DO-20-1021,18.22,1
502,DO-AL-0002,22,755,-0.298379,-0.296017,-0.293633,-0.284551,-0.286319,-0.268981,-0.241560,...,-0.294808,-0.302189,-0.302192,-0.302156,5,AL,AL,DO-AL-0002,57.42,5
503,DO-40-2006,22,750,-0.299355,-0.299788,-0.293633,-0.287729,-0.294508,-0.268981,-0.242107,...,-0.294808,-0.302189,-0.302201,-0.302156,1,40,40,DO-40-2006,12.58,1

In [11]:
data_cfc_with_cfc.to_csv('/home/rachel/Desktop/mm-vae data/caloric_restriction_DO_mice/data_with_cfc.csv')